---

plugins:
  - jest

env:
  node: true

extends:
  - 'eslint:recommended' 
  - 'airbnb-base' 
  - 'plugin:import/recommended'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - js: always
    

