name: test-and-linter
on:
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm ci
      - name: test
        run: npx jest
      - name: lint
        run: npx eslint .
